server {
    listen 80 default_server;
    server_name 112.124.35.179;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 308 https://112.124.35.179$request_uri;
    }
}

server {
    listen 443 ssl default_server;
    server_name 112.124.35.179;
    server_tokens off;
    client_max_body_size 2m;

    ssl_certificate /etc/letsencrypt/live/yujianxingji-ip/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/yujianxingji-ip/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:YujianTLS:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    location / {
        proxy_pass http://127.0.0.1:8787;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
